const permissions = [
  ['dashboard.view', 'Dashboard', 'Overview', 'View dashboard overview'],
  ['inventory.view', 'Inventory', 'Inventory', 'Open inventory module'],
  ['items.view', 'Inventory', 'Items', 'View items'],
  ['items.create', 'Inventory', 'Items', 'Create items'],
  ['items.update', 'Inventory', 'Items', 'Edit items'],
  ['items.archive', 'Inventory', 'Items', 'Archive and restore items'],
  ['items.delete', 'Inventory', 'Items', 'Permanently delete items'],
  ['items.stock_entry', 'Inventory', 'Items', 'Create stock entries'],
  ['items.adjust_stock', 'Inventory', 'Items', 'Adjust stock'],
  ['categories.view', 'Inventory', 'Categories', 'View categories'],
  ['categories.manage', 'Inventory', 'Categories', 'Create, edit, archive, and restore categories'],
  ['categories.delete', 'Inventory', 'Categories', 'Permanently delete categories'],
  ['suppliers.view', 'Inventory', 'Suppliers', 'View suppliers'],
  ['suppliers.manage', 'Inventory', 'Suppliers', 'Create, edit, archive, and restore suppliers'],
  ['suppliers.delete', 'Inventory', 'Suppliers', 'Permanently delete suppliers'],
  ['purchase_orders.view', 'Inventory', 'Purchase Orders', 'View purchase orders'],
  ['purchase_orders.create', 'Inventory', 'Purchase Orders', 'Create purchase orders'],
  ['purchase_orders.update', 'Inventory', 'Purchase Orders', 'Edit purchase orders'],
  ['purchase_orders.receive', 'Inventory', 'Purchase Orders', 'Receive purchase orders'],
  ['purchase_orders.cancel', 'Inventory', 'Purchase Orders', 'Cancel purchase orders'],
  ['stock_movements.view', 'Inventory', 'Stock Movements', 'View stock movement ledger'],
  ['fleet.view', 'Fleet', 'Fleet', 'Open fleet and dispatch module'],
  ['drivers.view', 'Fleet', 'Drivers', 'View drivers'],
  ['drivers.create', 'Fleet', 'Drivers', 'Create drivers'],
  ['drivers.update', 'Fleet', 'Drivers', 'Edit drivers'],
  ['drivers.archive', 'Fleet', 'Drivers', 'Archive and restore drivers'],
  ['drivers.delete', 'Fleet', 'Drivers', 'Permanently delete drivers'],
  ['drivers.view_balance', 'Fleet', 'Drivers', 'View driver balances'],
  ['stock_requests.view', 'Fleet', 'Stock Requests', 'View stock requests'],
  ['stock_requests.create', 'Fleet', 'Stock Requests', 'Create stock requests'],
  ['stock_requests.update', 'Fleet', 'Stock Requests', 'Edit stock requests'],
  ['stock_requests.accept', 'Fleet', 'Stock Requests', 'Accept stock requests'],
  ['stock_requests.complete', 'Fleet', 'Stock Requests', 'Complete stock requests'],
  ['stock_requests.cancel', 'Fleet', 'Stock Requests', 'Cancel stock requests'],
  ['stock_requests.print', 'Fleet', 'Stock Requests', 'Print accepted stock requests'],
  ['payments.view', 'Fleet', 'Payments', 'View payments'],
  ['payments.create', 'Fleet', 'Payments', 'Record payments'],
  ['reports.view', 'Reports', 'Reports', 'View reports'],
  ['team.view', 'Team', 'Users', 'View users and roles'],
  ['users.manage', 'Team', 'Users', 'Create and edit user accounts'],
  ['roles.manage', 'Team', 'Roles', 'Create roles and assign permissions'],
  ['audit_logs.view', 'Audit', 'Audit Logs', 'View audit logs'],
  ['settings.manage', 'Configuration', 'Settings', 'Manage system configuration'],
  ['driver_portal.view', 'Driver Portal', 'Requests', 'View own driver portal requests']
].map(([key, module, feature, description]) => ({ key, module, feature, description }));

const allPermissionKeys = permissions.map((permission) => permission.key);

const defaultRolePermissions = {
  admin: allPermissionKeys,
  inventory: [
    'inventory.view',
    'items.view',
    'items.create',
    'items.update',
    'items.archive',
    'items.stock_entry',
    'items.adjust_stock',
    'categories.view',
    'categories.manage',
    'suppliers.view',
    'suppliers.manage',
    'purchase_orders.view',
    'purchase_orders.create',
    'purchase_orders.update',
    'purchase_orders.receive',
    'purchase_orders.cancel',
    'stock_movements.view'
  ],
  accountant: [
    'fleet.view',
    'drivers.view',
    'drivers.create',
    'drivers.update',
    'drivers.archive',
    'drivers.view_balance',
    'stock_requests.view',
    'stock_requests.create',
    'stock_requests.update',
    'stock_requests.accept',
    'stock_requests.complete',
    'stock_requests.cancel',
    'stock_requests.print',
    'payments.view',
    'payments.create'
  ],
  driver: ['driver_portal.view']
};

module.exports = { permissions, allPermissionKeys, defaultRolePermissions };
